### ISSUE TITLE
New release with latest critical changes

### ISSUE THREAD

**Issue by rjherrera** [SoftwareBrothers/active_skin#43]
Are there any plans to release the changes already available in master? The last version available in ruby-gems is 0.0.12 (october 2015), and it is very outdated.

Since some of the changes like the bugfix for google fonts issue are critical (without them this gem wont work with rails >= 6.0.1), could you please release a new version of this gem?

I know we can reference the master branch in our gemfiles but I think that it is not the best way as it goes against the purpose of locking specific versions.

@wojtek-krysiak maybe you can give us some hope regarding this topic 🙏! Thank you!

**Comment by wojtek-krysiak** [comment]
@rjherrera just published the latest version - 0.0.13.

**Comment by rjherrera** [comment]
@wojtek-krysiak thanks you!
